version: "2"

services:
  web:
    extends:
      file: base.yml
      service: web
    build:
      args:
        - DJANGO_ENV=dev
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./webappdjango:/webappdjango
    ports:
      - "8000:8000"
